version: "3"

services:
    visualizador:
        image: dockersamples/visualizer
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 8090:8090
        deploy:
            placement:
                constraints:
                    - node.role == manager
                    
    receitadespesaservice:
        image: beatrizbrffiap/receitadespesaservice
        ports:
            - 8080:8080
        restart: always
        depends_on: 
          - db # This service depends on mysql. Start that first.
        environment: # Pass environment variables to the service
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/DBreceitaDespesa?useTimezone=true&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: R@@t2020     
        networks: # Networks to join (Services on the same network can communicate with each other using their name)
          - beatrzbrf11
   
    db:
        image: beatrizbrffiap/mysql-image
        ports:
            - "3306:3306"
        deploy:
            replicas: 3
            restart_policy:
                condition: on-failure
                max_attempts: 3
        networks:
            - beatrzbrf11
            
    angular-service: # The name of the service
        image: beatrizbrffiap/receitadespesaservice
        container_name: angularcontainer  # Container name
        build: ./angulardockerproject # Location of our Dockerfile
        depends_on: 
          - receitadespesaservice # This service depends on mysql. Start that first.
        volumes: # Volume binding
            - './angulardockerproject:/usr/src/app' 
        ports: 
            - '4200:4200' # Port mapping
        command: > 
            bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"     
        networks:
            - beatrzbrf11   
networks: 
    beatrzbrf11:
        external: true
